libjas/codegen.c, libjas/include/codegen.h
This pull request implements a wrapper function that allows the users to generate the raw assembly code without the hassle of setting up an array of instructions. This is more convent for apps like JIT compilers and compilers that can give enhanced error messages as well (ig)
=> Allowing the generation of a single instruction

libjas/encoder.c, libjas/include/operand.h, libjas/operand.c, tests/operand.c
This pull request added the functionality to allow the size of the offset to be *variable* and not defaulted to `OP_MODRM_DISP32`. With this change, all displacement sizes are originally set to a single byte wide (`OP_MODRM_DISP8`) and expands up to a 4 bytes-wide displacement. Having the option to expand up to 4 bytes gives the flexibility and allows the assembler to omit any extra 0s appended to the end.
=> Added support for varying displacement sizes 

libjas/encoder.c
Commit details:
> Changed typcast for offsets from `uint8_t`s to a signed `int8_t` as well as the signed double-worded counterpats, as specified in commit c78baced5e91160be835d4c90204c5eb10fb0ab0 where the offset type was changed to a signed value. (Specified in the Intel man- ual as well!)
>
>
> Note - The 4 byte displacement offset is NOT typed as `uint32_t` or any 4 byte-sized data type due to the `buf_write` function requiring an array of `uint8_t`s. However, they have been bunched together in a int32_t value with is abstracted as an unsigned char array?!?!?
=> Changed type

libjas/encoder.c, libjas/include/encoder.h
This Pull request describes the changes of the encoder function signature macro `DEFINE_ENCODER`'s move to the `encoder.h` header file as well as added documentation
=> Encoder macro changes/refactor

libjas/codegen.c, libjas/include/codegen.h
For some reason the `assemble_instr` funcitonc cannot be called using the `inline` keyword aimed at reducing production code size, and produces a linker error during link-time.
=> Removed `inline` attribute to the function signature

libjas/codegen.c, libjas/include/instruction.h, libjas/instruction.c
This branch describes the introduction and implementation of the `insert_get_tab()`. As outlined in the commit messages, this function will take in a instruction structure and fetch the corresponding instruction encoder table by looking up a specific table and sorting through a list of identities, similar to quadratics if you recall from school ;).
=> Added `instr_get_tab()`

libjas/codegen.c
This pull just simply refactored a if statement with the `INSTR_DIRECTIVE` macro as described in the commit message:
> Since the introduction of the `INSTR_DIRECTIVE` which does a check for if a enumeration is a directive instruction or not by casting it into a integer and comparing the values against the last instr- uction; somehow, this if statement was lost during the migration process (somewhere)
=> Use the `INSTR_DIRECTIVE` macro

libjas/instruction.c
This pull request describes the changes of removing and renaming of redundant pre processor functions, namely the `pre_default` pre processor function has been removed from many `OP_ZO` encoder identities due to its redundant nature, causing it to be 'doubled up' with the `op_identify()` function.
=> Changes to preprocessor functions

CONTRIBUTING.md
This Pull request describes the changes that finally concludes the writing of the Jas contribution guide, in particular, this Pull request adds in the common changes and items for developers such as adding new assembler instructions and encoder functions.
=> Contributing guide changes

libjas/codegen.c, libjas/encoder.c, libjas/include/encoder.h, libjas/include/instruction.h, libjas/instruction.c, libjas/operand.cpp, tests/operand.c
This Pull, the encoder module received minor updates and changes including function and enum renaming as well as minor refactoring works carried out. Notably, the lookup table for encoders has been moved from the instruction module over to the encoder module and **all encoder functions must be call through this function**, encoder functions shall not be called directly. More details appear in the commit logs
=> Encoder identity refactoring changes

libjas/codegen.c
Stupid me here again - previously in some random commit I somehow added the `label_get_size` function **pointer** itself as the com- parison with the `i` variable, now, we are *actually* invoking the funciton and getting the correct label table size
(See, this is why we read compiler warnings and error messages 😝)
=> Fixed label table by invoking funciton

CONTRIBUTING.md, libjas/include/instruction.h, libjas/instruction.c
This pull request describes several changes that has allowed for better readability in the very crowded and complex `instruction.c` file (The file that has described the instruction encoder reference tables). This branch has not only reduced redundant and repetitive code blocks but has also added redundancy and measures to prevent incorrect encoding. Check the commit logs for more information. This is just a short description for the log. ;)
Alvin.
=> Instruction table refactor

libjas/include/operand.h, libjas/operand.c, tests/operand.c
This commit has added the `op_write_opcode` funciton, this funciton intends to replace the old and weird `OP_OPCODE_HELPER` macro that attempts to write a opcode using macro functions and without much consideration about other variable condiitons.
=> Added `op_write_opcode()` function

libjas/encoder.c
This pull implements the `op_write_opcode` function into the `encoder.c` source file, replacing the old `OP_OPCODE_HELPER` function in favour of the new opcode writer function. (As described in pull request #22, please see #22 for more information)
Basically, (In a nutshell), I just did a find and replace of all the old `OP_OPCODE_HELPER` macro calls with a invocation of the new `op_write_opcode` function
=> Implementation of opcode function

libjas/encoder.c
This pull has added information for the `i_commom()` internal encoder function for writing immidiate function. Since this function is only used in the `enocder.c` (and is static) making the funtionality very un-clear for callers, (also without a corrisponding header)
=> Added internal docs for `i_common`

libjas/operand.c
Happy new year, this pull has revised the `op_write_opcode` function, which was previously mis-interpreted. According to the Intel x86 docs, a instruction **including** a byte-sized operand **MUST** use the byte instruction opcode. This is demonstrated in the MOVZX instruction's docs on 4-136 Vol. 2B where a seperate opcode is used with `r/m8`.
=> Revised `op_write_opcode` function

libjas/include/instruction.h, libjas/instruction.c
This pull added support for the MOVZX instruction (Move with zero- extend). Although this pull have not added the required unit tests for this instruction (None of the instruction other than `mov` for a matter of fact), this pull has added the MOVZX instruction's co- rrisponding encoder table as well as its enum entry in `instruction.h`
=> Added support for MOVZX

libjas/include/instruction.h, libjas/instruction.c
The `MR` and `RM` identies are very very similar, they both use the same operand type - namely registers and also what Intel refers as `m` (memory) locations. Due to the `MR` identity being put before the `RM` identity in `encoder.h`'s `enum enc_ident` enumeration, the assembler has always had a tendency to use the `MR` encoder enum identity when a register and memory location is expressed. This is very problematic when the assembler matches the operand types with some instructions that *don't support* the `MR` identity, causing an opcode error to be thrown.
Therefore to prevent the confusing behavior, we'll need to manually override this behavior by *manually* adding a if condition to change it when able.
=> Fix mr rm ident clash

libjas/instruction.c
Since the introduction of the `has_byte_opcode` member in the `instr_encode_table` struct in #21, basically no instruction encode table *actually* uses this member of the struct; casuing mis- interpretation and usage of this member in other functions and modules. This pull has added this boolean value to *most* instruction encoder tables, in order to support functions and conditionals that depend of this member exisiting.
=> Added `has_byte_opcode` member to every table

README.md
` instruction_t instr[] = (instruction_t[]) {`
This line instantly caught my eye. This isn't proper C. If this compiles, it's because of a GNU extension. The true C way is simpler:
` instruction_t instr[] = {`
=> Fix readme example that isn't proper C

libjas/instruction.c
This pull has added the `no_operands` pre-processor function, this function aims to prevent callers and users accidentally passing operands into instructions which carries the `ENC_ZO` identity in which they do not require any operands.
Furthermore, this pull (albiet not very the niche with this pull's "agenda") has also corrected the `nop` instruction which previously had the instruction encoder table values switched around, casuing the opcode to be read as the opcode extention and the opcode extention to be read as the *real opcode*
=> Added pre-processor function for `ENC_ZO` identities

libjas/instruction.c, libjas/operand.cpp
This pull has fixed the strange encoders clash between the O and I
encoder functions, previously the encoders O and I were both to be
thought as one `imm` (immediate value) operand on the first operand
location.
Upon futher review, it was found that the I operand encoder function
identity consists of a `imm` operand **exclusively** and does not
contain any more oprands. Contary to the I identity, the O identity
**ALSO** contains a **accumulator** as the first operand and a `imm`
**following** the **accumulator** instead.
=> Fix encoder clash

TODO.txt, libjas/include/instruction.h, libjas/instruction.c
This pull has added complete support for the MOVSX (Move with sign extension) instruction, since this instruction exhibits very similar encodings to the previously implemented MOVSX instruction, many encoding functionality and encoder tables can be *shared* (Such as pre-processors and opcods)
Although this pull is listed as only adding support for the MOVSX instruction, this pull has also renamed the `pre_movzx` pre-proces- or function `pre_small_operands` to better encapsulate its behavior and allowing cross-usage to other instruction enocder tables.
=> Added support for MOVSX

libjas/instruction.c
In the previous pull - #32 where the `pre_movzx` pre-processor was renamed to `pre_small_operand_sizes`, the error message was not changed and remained to shown as a "MOVZX" instruction fault as per the patch. This pull has corrected the error message to point to both the MOVZX and MOVSX instructions instead.
=> Fixed error message

libjas/include/instruction.h, libjas/instruction.c
Added support for the `xchg` instruction (Exchange register/memory with registers) by adding the instruction encoder table.
=> Added instruction support for `xchg`

libjas/instruction.c
This pull has addded a "edge case" for the `INSTR_NULL` cases that may be passed into the `instr_get_tab` funciton. Further testing has found that this function may be problematic and force segmentation faults when faced with a `NULL` value in either the operands or `instr` member. Now, this function will intentionally skip any `NULL` or `INST- R_NULL` values.
=> Added case for `NULL` instructions

libjas/include/operand.h, libjas/operand.c, tests/operand.c
Since addition and support of the `lable` member of the `operand_t` structure, this funciton, `op_construct_operand` has never supported this member, disallowing the usage and referencing of labels in the assembler.
=> Added label member support to `op_construct_operand`

libjas/instruction.c
For some completely random and obscure reason, when using the `-O3` or whatever optimisation other than the default, the `instruction.c` unit test testing against the `instr_gen` function breaks when called, further digging has revealed for some reason, the `data` value is not being assigned with the required value. (and instead holds a completely insane in place).
This pull has combined the two statements into a compound literal, red- ucing complexity to the code which prevents it from being "optimised" out of the program and therefore breaking whenever a optimisation flag is set in the compiler options.
=> Fixed issue with register not assigning to operand

libjas/codegen.c, libjas/exe.c, libjas/include/exe.h
This pull has introduced a pointer argument to the `exe_sect_header` function to allow the function itself to modify the size value *out side* of the function to help the caller (Which in this case is nor- mally the `codegen` function) keep track of the total offset and size of the headers before the sector of the start of the contents of the ELF file. (Where the code, secttion table and everything else goes)
=> Added pointer for tracking offset changes

libjas/include/instruction.h, libjas/instruction.c
This pull has added support for the `bswap` instruction in the jas assembler, by adding a new instruction encoder table with the O encoder identitiy, we can easily implement a new instruction as such.
=> Added support for `bswap` instruction

libjas/instruction.c, libjas/pre.c
This pull has moved over all the pre processor functions from
the `instruction.c` file. Since the `instruction.c` file is already
fairly crowded from all the instruction encoder tables (With more
coming soon), there was no reason for the pre-processor functions
to be crowding around with no direct benefits to the tables *itself*
Therefore, these pre-processors has been ported over to a new file
and included *directly* (Which I know is relatively bad practice)
=> Refactor and isolate pre processors

libjas/exe.c
After the switch to updating the ELF offset using pointers to allow the offset value to be updated automatically within the function. Some other functionality has broke since the changes in #39 and as outlined above. First of all, the outstanding issue causing issues after the change is the "pre mature" modification of the offset before it was used.
In particular, the modification line:
> *off += sect_sz;
Was placed **before** the line where *it was used*:
> buf_write(&ret, (uint8_t *)off, 8);
This means, the value is incorrectly referenced, however, this is not the primary issue *(I think)*. The primary issue I think is the fact that I am referencing the pointer to the `off` pointer.
Previously, the offset was written as `&off` which is the **address** of `off`, instead of the value.
=> Fixed incorrect offset values.

libjas/codegen.c, libjas/encoder.c
This pull has removed the usage and definiton of the `is_pre` global variable that was used to define the state of the assembler (As the name suggests, if the assembler was in the pre-processor state for resolving labels, or in the primary assembling mode.)
To reduce naming clashes, reliance on external variables that can be reliant on unreliable external sources, these variables are better off removing them. (a. I'm going to forget them, or b. I'll be very confused managing them) Besides, it's never good for a function to rely on anything other than its parameters.
Believe it or not, the global variable in the `codegen.c` file and the `encoder.c` file was **completely not required**, there was absolutely *no reason* for the global variable to *exist*.
Since the global variable was used …
=> Removed usage of `is_pre` globally (See below)

README.md, libjas/include/instruction.h, tests/instruction.c
This pull has added operand generation "helper" macros for the `instr_gen()` function, allowing callers to write simpler and less confusing functions with less boiler-plate code
Previously, to write a `mov rax, 0` instruction you had to call:
> `instr_gen(INSTR_MOV, 2, OP_R64, REG_RAX, 0, OP_IMM64, 0, 0);`
Now, the caller can use the macro to *automatically fill* the operands like so:
> `instr_gen(INSTR_MOV, 2, r64(REG_RAX), imm64(0));`
Theres less clutter, and we can easily read it without manually counting arguments.
=> Added macros for working with `instr_gen()`

libjas/include/label.h, libjas/label.c
This pull has added the `label_gen()` funciton, this function is a similar `instr_gen` *corrisponding counterpart* to the `instr_gen` function, but as the name suggests, for generating labels. This funciton takes in a label `name` and `type` as arguments (as documented).
=> Added `label_gen()` funciton

libjas/include/instruction.h, libjas/instruction.c
This pull has added the `instr_write_bytes()` function which is similar/ equivilent to the `db` directive in the usual NASM syntax, this new function takes in a size and uses varidict arguments to define the x amount of bytes as passed into the size argument. For more information, see patch file and/or changelog
=> Added `instr_write_bytes()`

libjas/tabs.c
This pull has renamed the corrispondign `div` instruction encoder table for the `div` instruction to `_div` (With a underscore), since C does not have a namepace mechanics by default, there could be po- tential naming clashes and conflicts when calling this instruciton enocder table. (Compiler flagged errors and warnings may also exist)
=> Renamed `div` instruction table with underscore

libjas/instruction.c
Fixed `instr_gen` function
After some days of debugging later, (well, it was very very confusing)
the root issue for the incorrect instruction was finally found.
Since all local variables in C included within a funciton is stored on
the stack frame, it will get cleaned-up after the function exits/returns,
therefore, when `instruction_t` struct was returned from the `instr_gen`
function, we were reading from the *stack frame* instead of *actual
memory*. After other functions were called, the stack frame where the
previous `instruction_t` struct was stored was overwitten ang and placed
back in with some random garbage.
This pull is a *almost stub* implementation/fix for the `instr_gen` function,
in particular, it allows memory to be allocated dynamically to support the
storage of these …
=> Fix instr gen

libjas/Makefile
Since the removal and deprecated optimisation flag `-Ofast` providing un-supported and non-standard optimisations for speed was removed in subsequent versions of clang, this pull has removed this flag in favor for the next best optimisation of `-O3`
=> Removed `-Ofast` flag in favor of `-O3`

libjas/Makefile, tests/Makefile
After the addition of the `-Og` compiler flags in commit number 84908117baa3292d46ffc9cae7a5d4b4adf82e89, the lldb debugger has complained about a compiler optimsation issue and that many expression and variable evaluation functionality can be limited as documented in the llvm docs.
=> Removed -Og compiler flags

libjas/include/jas.h, libjas/instruction.c, libjas/label.c
After the fix in #50, which only covered the `instr_gen` function, this pull has taken a similar method in patching the other generation function for generating a `instruction_t` struct dynamically.
Please see #50
=> Added dynamic memory allocations to generators

libjas/pre.c
This pull has modified the `pre_imm` pre-processor function to allow many operand sizes where there is NOT an accumulator register, and also added a guard to prevent 64-bit sized immediate operands in the *second operand* position. As described in the `SUB` instruction of the Intel x64 manual, the MI opcode identity should not include a 64-bit corrisponding operand even though the first operand is a 64-bit memory location and shall follow the identity as described:
> Op/En  Operand 1            Operand 2
> MI	   ModRM:r/m (r, w)	imm8/16/32
Now, the encodings seems to be matching to the intel manual and the corrisponding encoded format of the instruction: `sub rax, 0x12345678` *does infact disassemble correctly*.
=> Minor patch: Modified guard to correct operand sizes

libjas/include/instruction.h, libjas/instruction.c, tests/operand.c
In the previous code (as shown in the patch file), the `instr_get_tab` function attemps to compare the `instr.instr` enumeration to the constance `NULL` value. Since the `NULL` value equates to the `INSTR_MOV` enum, it may cause incorrect readings and a compiler error as well 😝.
This pull has added a `INSTR_NOTHING` value to the `instructions` enum to seperate values and allow debugging processes to directly and clearly identify if an instruction is invalid, instead of defaulting to `MOV`.
=> Added filler element for `enum instructions`

libjas/encoder.c
In this pull, a previously not dereferenced pointer has been forced and casted into the `reg_needs_rex` funciton as shown below:
>``` !reg_needs_rex((enum registers)op_arr[0].data)```
This is immediately incorrect as a memory address may **not** just magically turn into a register, not without a de-reference to the pointer. This is further pronounced when we see that the function **itself** does not allow a pointer to be passed, so having a pointer forced into there is **very very very dangerous** (This is why we have rust lol 🦀).
=> Fixed type cast issue

libjas/instruction.c
This commit has updated the `alloc_operand_data` macro to allow it to safely allocate enough data when "popping" an argument from the stack for. Previously, the `va_arg` macro would promote some data sizes as `int`s and messing up other data types. This commit has just added a little "one size fits all" solution by allocating a 64-bit sized parameter.
=> Updated macro

libjas/encoder.c, libjas/include/encoder.h, libjas/instruction.c, libjas/operand.cpp, libjas/pre.c, libjas/tabs.c
This pull has added the support for the IN and OUT instructions in the Jas assembler, due to the unusual patterns of the encoding as documented in the Intel documentation, this instruction has been put off, and I've procrastinated for quite a while of adding the support for this instruction. Inparticular, instruction has non- standard operand encodin identity formats where the ZO identity was used to depict the use of the DX and AL *registers*, which **had operands**. (See the extact from below)
> Instruction	Op/En		64-Bit Mode
> EF		OUT DX, EAX	ZO
Since the in-consistency, a new encoder identity was implemented in this pull, namely a `ENC_IGN` idenity that is used as a little *default* value *other than* the `NULL` value, as seen in previous commits. This encoder identity will **ignore** …
=> Added support for IN and OUT instructions

libjas/include/instruction.h, libjas/include/operand.h, libjas/include/operand.hpp, libjas/include/register.h, libjas/operand.cpp, libjas/pre.c
This pull has removed the usage of the accumulator type such as the `OP_ACC64` and others in favor of using the already frequently used `OP_R64` and simply subbing in the `REG_RAX` value instead, also al- lowing the usage of the `acc` macro in other situations other than the supported instructions. Using these new operand types not only allows for more flexibility but also gives the same error handling the `REG` module would otherwise, allowing more common ground between types.
=> Removed the usage of the accumulator operand type

libjas/include/instruction.h
Documentation gap: users can be mis-lead and use the `instr_free()` function to free their own user-defined instructions, instead of jas-allocated structs.
=> Added documentation

libjas/instruction.c, libjas/label.c
Experimental: Utilise `malloc` instead of `strdup`
There have been portability issues associated with the (although C
standard) `strdup` funciton, which apparently is un-defined on linux
systems. This commit has opted to use the standard `malloc` and `strcpy`
it over to the destination.
=> Remove strdup for malloc

CONTRIBUTING.md, libjas/codegen.c, libjas/encoder.c, libjas/include/encoder.h, libjas/include/instruction.h, libjas/operand.c, libjas/tabs.c
Previously, the `has_byte_opcode` feild has been added to the `instr_encode_table` to show wether a instruction encoder table entry contains a byte opcode (An opcode used **only** when solely byte operands has been supplied). However, some of the instructions have inter-modal opcode sizes, for example the byte opcode can be 2 bytes long and where the standard opcode is only 1 byte long.
Previous efforts of adding a `0x90` to "pad" the opcode was used and retained the same functions of also just simple writing nothing. This pull has omitted this issue by changing the `has_byte_opcode` struct member as a `byte_opcode_size` field to allow it to indicate the pressence of a byte opcode **as well as** a size **at the same time** (Where a `byte_opcode_size` of > 0 and =< 3 means a present byte …
=> Changed `has_byte_opcode` into size field

libjas/compile.js, libjas/instructions.tbl
Previously and also as of the current codebase, everything (all the instruction enocder tables) have been represented in C and in a huge file of structs. (Not very maintainable or readable, frankly) This pull has added a compiler for a text-based format (`.tbl` files which the linux kernel also uses for kernel-system-calls).
In a nutshell, the `.tbl` file has options consisting of the corrisponding values in a equivilent C structure such as opcode, opcode extention and pre functions, with some changed. These values will be read and parsed, then produced into a C syntax to be fed into the compiler as C code. (For more information, please see the `instruction.tbl` file's comments)
=> Added text-based instruction table support

libjas/instructions.tbl
This pull has continued the migration of the instruction encoder bank from the previous `tabs.c` file to the new text-based file as per #74.
=> Migration of the `xor` and continuation of `or`

libjas/compile.js, libjas/tablegen.js
This pull solves and patches some formatting issues regarding the automatic generation of the instruction table; as well as the syntax errors when compiling it to the native C struct representation.
=> Changes to instruction encoder bank compiler scripts

libjas/instructions.tbl
This pull has seen the continued migration of the instruction enco-
der tables from the previous `tabs.c` file to a newer and better
text-based markup language, including the following instructions:
- not
- inc		
- dec		
- jmp
- je           
- jnz		
- jne           
- jz
- call		
- ret		
- cmp		
- push
- pop		
- in		
- out		
- clc
- stc		
- cli		
- sti		
- nop
- hlt		
- int 		
- syscall	
- movzx
- movsx
=> Continued instruction encoder bank migration

libjas/compile.js, libjas/tablegen.js
In the compiler script for the text-based instruction enocder bank,
the C compiler has encountered issues where when the array was gen-
erated as `NULL` pruely, it reconised the following elements as the
*members* of the array rather than sibling elements *inside the object*.
The exclusion of quotes in the empty array has also lead to the
throwing of the error: "Invalid integer conversion resulting from
truncation", which supports the relavant assumption that the struct
members has been parsed as array members instead.
Also, a guard clause has also been added to check if the grouping of
the byte opcode, writing in `0` as the byte opcode size if its set as
`NULL`. Previously the compiler has mis-read it has `1` since it counted
the number of commas, defaulting to `1` as the default opcode …
=> Minor script changes

Makefile, libjas/Makefile, libjas/instructions.tbl, libjas/tabs.c
This commit has finally completed the migration of **all** the instruction encoder tables, as introduced from pull request #76. This pull saw completion of the instruction enocder table, concluded with the cmovcc set of instructions.
=> Completely finished migration to text--based markup

libjas/label.c
In the `label_free()` function, the function attempted to call `free` on the basis of the pointer to the allocated memory, rather than the actually memory that had to be freed. Ultimately, causing the program to throw a *"pointer freed has not been allocated"* error during run- time. This issue arose since I have attempted to use the pointer of a pointer to the allocated data to allow the pointer to updated by ref- erence, making it more seemless. But, this ended in tradgity lol.
=> Dereferenced the pointer to free the correct pointer

libjas/Makefile, libjas/instructions.tbl
Some fixes regarding mis-read or mistaken encoder bank values such as encoder operands and/or opcodes. Mostly **human-errors** no signs of issues on the `compile.js` or `tablegen.js` scripts.
=> Encoder bank fixes

libjas/include/operand.h, libjas/instruction.c, libjas/operand.c
This pull has completed several refactoring works conducted for the `operand.c` file, as shown below, please consult the patch file for a more detailed changelog, take this as a TL;DR or a justification:
- Removed `op_construct_operand` function This pull has seen the removal of the `op_construct_operand` function, this function has been of no (or little) use of the assembler and has been sitting as a pile of junk, taking up space and building complexity in the codebase where the objectives could've been acheived using a simpel object-literal (Albeit a bit unpleasing to our eyeballs)
- Modified/omitted error messages (Will soon be done to whole codebase) This pull has also changed certain error messages for the sake on consistency among other command line tools. Most command line tools do …
=> Carried out refactoring for `operand.c`'s module

libjas/encoder.c
This pull has added error checking for the `ref_label` function, raising an error to the calleee if a 64-bit sized label is given. Furthermore, a more streamlined way to handeling errors using labels has also been implemented using `goto`s to reduce code.
=> Added size error checking for `ref_label`

libjas/encoder.c
This pull has removed the operand check rule implemented in a previous attempt to remove pre-processor functions. However, some instructions **does** in fact allow the different sizes of operands. For a matter of fact, the `movzx` instruction **MUST** have a different size to allow it to extend the trailing zeros at the end of a smaller operand.
=> Removed operand check

libjas/instructions.tbl, libjas/operand.c, libjas/pre.c, libjas/scripts/compile.js
This pull has removed the `pre_in_out` pre-processor applicable for the `in` and `out` instructions. In particular, these instructions does not allow the use of operands other than 8-bit operands, this pull has modified the `op_write_opcode` to allow the function to catch certain in consistencies which may violate these rules. Instructions which use this behavior should leave the "normal" opcode empty, only providing the `byte_instr_opcode`.
=> Removed the `pre_in_out`

libjas/include/dir.h, libjas/include/instruction.h, libjas/instruction.c, libjas/label.c
Since the association of the directives being a similar format of instructions in jas (`instruction_t`), the instruction format has become overly complex and polluted of different operands, inputs and properties, unclear of correlation either to `enum instructions` or as part of the poorly designed `INSTR_DIR` prefixes. Since the integration of *unionised* directives, this pull has moved code associated with such behaviour outside to avoid wrongfully associating directives to be equivalent or similar to instructions.
From this point onwards, it should be noted that all `instruction_t` structs, as dubbed the `instr` property, **must** not deviate from documented x86 instructions. `instruction_t`, or any associated enums should not be used as part of custom information for the jas …
=> Moved directives to its own isolated file of `dir.h`

libjas/codegen.c
Previously, for some strange reason, the *`valid_operands`* boolean value has been setup to check with a negated boolean logic operator. Hence, all instructions that have been deemed *"valid"* by jas would have been flagged as having an "invalid operand type".
=> Fixed incorrectly labled conditonal validator

libjas/encoder.c
Quick and dirty fix for the broken `mi` ident, will eventually fix when the encoder logic is re worked.
=> Removed operand checking for `mi`
